const offensiveWords = {
  racialSlurs: [
    "nigga",
    "nigger",
    "chink",
    "gook",
    "jap",
    "slope",
    "slant",
    "zipperhead",
    "spic",
    "beaner",
    "wetback",
    "cracker",
    "honky",
    "gringo",
    "redskin",
    "savages",
    "sandnigger",
    "camel jockey",
    "towelhead",
    "terrorist",
    "wog",
    "kike",
    "heeb",
    "gypsy",
    "pikey",
    "wop",
    "dago",
    "paki",
  ],
  culturalOrReligiousInsults: [
    "infidel",
    "heathen",
    "zionist",
    "islamist",
    "jihadi",
    "muzzie",
    "christ-killer",
  ],
  genderOrSexualityInsults: [
    "sissy",
    "tranny",
    "queer",
    "fag",
    "dyke",
    "homo",
    "nancy boy",
  ],
  mentalOrPhysicalHealthInsults: [
    "psycho",
    "retard",
    "lunatic",
    "schizo",
    "spaz",
  ],
  slangForAsians: [
    "chink",
    "gook",
    "jap",
    "nip",
    "rice nigger",
    "yellow skin",
    "oriental",
    "dog eater",
    "bat eater",
  ],
  blackOrAfricanInsults: [
    "nigga",
    "nigger",
    "monkey",
    "jigaboo",
    "coon",
    "spook",
    "sambo",
    "tar baby",
    "cotton picker",
    "porch monkey",
    "ape",
    "jungle bunny",
  ],
  whiteOrEuropeanInsults: [
    "cracker",
    "honky",
    "white trash",
    "redneck",
    "hillbilly",
    "gringo",
    "pasty",
    "pale face",
    "mayo",
  ],
  hispanicOrLatinoInsults: [
    "spic",
    "beaner",
    "wetback",
    "greaser",
    "border hopper",
    "pepper belly",
    "mojado",
    "taco bender",
    "cholo",
  ],
  middleEasternInsults: [
    "sandnigger",
    "camel jockey",
    "towelhead",
    "terrorist",
    "raghead",
    "aladdin",
    "bomb maker",
    "desert monkey",
  ],
  nativeAmericanInsults: [
    "redskin",
    "injun",
    "savage",
    "wagon burner",
    "chief",
    "squaw",
    "teepee creeper",
    "corn shucker",
  ],
  jewishInsults: [
    "kike",
    "heeb",
    "jewboy",
    "hymie",
    "sheeny",
    "christ-killer",
    "penny pincher",
    "shylock",
  ],
  asianInsults: [
    "chink",
    "gook",
    "jap",
    "nip",
    "rice nigger",
    "slant-eye",
    "sloper",
    "yellow skin",
    "oriental",
    "dog eater",
    "bat eater",
  ],
  generalOffensivePhrases: [
    "go back to your country",
    "you people",
    "speak english",
  ],
};

export default offensiveWords;
